version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongo_db_2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-seed/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  api:
    build: .
    container_name: nest_api
    restart: always
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:secret@mongodb:27017/credit-simulator?authSource=admin
    ports:
      - "3000:3000"

volumes:
  mongodb_data: